version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7-slim

    working_directory: ~/aws-sm

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            pip install pipenv
            pipenv install --system --dev

      - run:
          name: run tests
          command: |
            py.test --tb=line

      - run:
          name: run flake8
          command: |
            flake8

      - run:
          name: run radon
          command: |
            radon cc -n C .
            radon mi -n B .
