version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-3.7
      - test-3.6
      - test-3.5
      - test-2.7
jobs:
  test-3.7: &test-template
    docker:
      - image: circleci/python:3.7-jessie
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Fish
          command: |
            echo "deb http://ftp.debian.org/debian jessie-backports main" | sudo tee /etc/apt/sources.list.d/jessie-backports.list
            sudo apt-get update
            sudo apt-get -t jessie-backports install fish
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          command: |
            pipenv install --system --dev
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
      - run:
          command: |
            py.test --tb=line --cov-report=html
      - store_artifacts:
          path: htmlcov/
      - run:
          command: |
            flake8
      - run:
          command: |
            radon cc -n C .
            radon mi -n B .
  test-3.6:
    <<: *test-template
    docker:
      - image: circleci/python:3.6-jessie
  test-3.5:
    <<: *test-template
    docker:
      - image: circleci/python:3.5-jessie
  test-2.7:
    <<: *test-template
    docker:
      - image: circleci/python:2.7-jessie
