version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-3.7
      - test-3.6
      - test-3.5
      - test-2.7
jobs:
  test-3.7: &test-template
    docker:
      - image: circleci/python:3.7
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - cache-{{ checksum "Pipfile.lock" }}
            - cache-
      - run:
          command: |
            export PIPENV_VENV_IN_PROJECT=true
            sudo pip install pipenv
            pipenv install --system --dev
      - save_cache:
          key: cache-{{ checksum "Pipfile.lock" }}
          paths:
            - ~/.local
            - ~/.cache
      - run:
          command: |
            py.test --tb=line --cov-report=html
      - store_artifacts:
          path: htmlcov/
      - run:
          command: |
            flake8
      - run:
          command: |
            radon cc -n C .
            radon mi -n B .
  test-3.6:
    <<: *test-template
    docker:
      - image: circleci/python:3.6
  test-3.5:
    <<: *test-template
    docker:
      - image: circleci/python:3.5
  test-2.7:
    <<: *test-template
    docker:
      - image: circleci/python:2.7
